[[plugins]]
    package = "@netlify/plugin-nextjs"

[build]
  command = "next build"
  publish = ".next"
  
[[headers]]
  for = "/app/api/*"
  [headers.values]
    Cache-Control = "no-store"
    CDN-Cache-Control = "no-store"