import { ReactNode } from "react";
import {
  CategoriesProvider,
  NextAuthProvider,
  NotificationProvider,
  ProgressBarProvider,
  QueryClientProvider,
} from "@/providers";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/providers";
import { Header } from "@/components/Header";
import { ProgressBar } from "@/components/ProgressBar";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <NextAuthProvider>
            <ThemeProvider>
              <NotificationProvider>
                <CategoriesProvider>
                  <ProgressBarProvider>
                    <Header />
                    <ProgressBar />
                    {children}
                  </ProgressBarProvider>
                </CategoriesProvider>
              </NotificationProvider>
            </ThemeProvider>
          </NextAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
